### ISSUE TITLE
Pinging cjdns returns a successful pong but Cjdns.php still fails to recognize it

### ISSUE THREAD

**Issue by khag7** [thefinn93/cjdns-php-gui#7]
https://github.com/thefinn93/cjdns-php-gui/blob/master/Cjdns.php#L77 checks for a response of "d1:q4:ponge" but another valid response that my sever is giving is "d01:q4:ponge"

Will make PR to verify succesful ping if last 5 characters match "ponge"

**Comment by thefinn93** [comment]
Cjdns.php is no longer maintained by me, this repo is kind of dead. @dansup maintains a newer version I believe

**Comment by khag7** [comment]
I did see that you haven't maintained this over the years, but its the only PHP web interface for cjdns I could find. Figured I'd get a few little bugs worked out for ya. If you have no interest in maintaining it I can refrain from submitting PR's to you.

**Comment by thefinn93** [comment]
No it's not that, it's that I think @dansup's version is better and like more maintained. Lemme ping him on IRC

**Comment by khag7** [comment]
Ok. I will look and see what he has. Let me know what you figure out.

**Comment by thefinn93** [comment]
He's also not at a computer. He'll be around in like 30 min. Are you connected to hyperbaria? If so, hop on `irc.fc00.io` and chat with him

**Comment by khag7** [comment]
Thanks for the help. I'm all caught up now. This project was merged into the cjdns contrib directory and has since been maintained there.

**Comment by thefinn93** [comment]
Ah. Cool. I should update the README to say that...
